"""기본 설명 모음"""
from fastapi import status

__all__ = ("STATUS_CODE_DESCRIPTION",)

STATUS_CODE_DESCRIPTION = {
    # 1xx: 임시적인 상태를 나타냅니다.
    status.HTTP_100_CONTINUE: "서버가 요청의 첫 부분을 잘 받았고, 클라이언트는 나머지 정보를 계속 보내도 된다는 신호입니다.",
    status.HTTP_101_SWITCHING_PROTOCOLS: "클라이언트가 요구한 대로, 예를 들어 WebSocket 같은 다른 통신 규약으로 서버가 바꿔 연결하고 있습니다.",
    status.HTTP_102_PROCESSING: "서버가 요청을 받았으며 처리하고 있으나, 아직 답변할 준비가 되지 않았음을 알립니다.",
    status.HTTP_103_EARLY_HINTS: "최종적인 HTTP 메시지가 오기 전에, 서버가 미리 일부 응답 헤더를 보내는 데 쓰입니다.",
    # 2xx: 요청이 성공적으로 처리되었음을 나타냅니다.
    status.HTTP_200_OK: "요청이 성공적으로 처리되었고, 결과 데이터가 응답에 포함되어 있습니다.",
    status.HTTP_201_CREATED: "요청에 따라 성공적으로 새로운 리소스가 만들어졌습니다.",
    status.HTTP_202_ACCEPTED: "요청은 받아들여졌지만 아직 처리가 완료되지는 않았습니다.",
    status.HTTP_203_NON_AUTHORITATIVE_INFORMATION: "서버가 원본 서버로부터의 정보를 변환하여 제공하고 있지만, 원본의 정보와 정확히 일치하지는 않을 수 있습니다.",
    status.HTTP_204_NO_CONTENT: "서버가 요청을 성공적으로 처리했으나, 반환할 내용이 없습니다.",
    status.HTTP_205_RESET_CONTENT: "서버가 요청을 성공적으로 처리했으나, 반환할 내용은 없고, 요청자는 화면을 초기화해야 합니다.",
    status.HTTP_206_PARTIAL_CONTENT: "클라이언트가 요청한 범위에 따라서, 서버는 리소스의 일부만 전송하고 있습니다.",
    status.HTTP_207_MULTI_STATUS: "응답이 XML 형태로 여러 개의 상태 코드를 포함할 수 있으며, 각각의 상태 코드는 다른 하위 요청의 결과를 나타냅니다.",
    status.HTTP_208_ALREADY_REPORTED: "WebDAV에서 사용되며, 이미 다른 곳에서 보고된 리소스의 멤버는 여기에서는 다시 나타나지 않습니다.",
    status.HTTP_226_IM_USED: "서버가 GET 요청을 충족시켰고, 응답은 한 개 이상의 인스턴스 조작의 영향을 받은 리소스의 상태를 나타냅니다.",
    # 3xx: 요청을 완료하기 위해 추가 동작이 필요함을 나타냅니다.
    status.HTTP_300_MULTIPLE_CHOICES: "여러 개의 가능한 옵션이 있으며, 클라이언트는 이 중에서 하나를 선택해야 합니다.",
    status.HTTP_301_MOVED_PERMANENTLY: "요청한 리소스가 새로운 URI로 영구적으로 이동했습니다. 앞으로 이 주소를 사용해야 합니다.",
    status.HTTP_302_FOUND: "요청한 리소스가 일시적으로 다른 위치로 옮겨졌습니다.",
    status.HTTP_303_SEE_OTHER: "응답을 찾기 위해 다른 URI에서 GET 방식으로 요청을 해야 합니다.",
    status.HTTP_304_NOT_MODIFIED: "요청한 리소스가 마지막 요청 이후로 변경되지 않아서, 다시 보내지 않아도 됩니다.",
    status.HTTP_305_USE_PROXY: "요청된 리소스는 지정된 프록시를 통해서만 접근 가능합니다.",
    status.HTTP_306_RESERVED: "이 코드는 과거에 사용되었지만 현재는 예약되어 있으며 사용되지 않습니다.",
    status.HTTP_307_TEMPORARY_REDIRECT: "현재 요청은 다른 URI로 임시로 리디렉션되지만, 미래의 요청은 원래 URI를 사용해야 합니다.",
    status.HTTP_308_PERMANENT_REDIRECT: "현재 요청과 모든 미래의 요청은 새로운 URI를 통해 이루어져야 합니다.",
    # 4xx: 클라이언트의 요청이 잘못되었음을 나타냅니다.
    status.HTTP_400_BAD_REQUEST: "서버가 요청을 이해하지 못했습니다. 잘못된 요청 구조입니다.",
    status.HTTP_401_UNAUTHORIZED: "이 작업을 수행하려면 인증이 필요합니다.",
    status.HTTP_402_PAYMENT_REQUIRED: "이 상태 코드는 현재 사용되지 않지만, 미래에 사용될 수 있도록 예약되어 있습니다.",
    status.HTTP_403_FORBIDDEN: "서버가 요청을 알아들었지만, 실행을 거부하고 있습니다.",
    status.HTTP_404_NOT_FOUND: "서버가 요청한 페이지나 자원을 찾지 못했습니다.",
    status.HTTP_405_METHOD_NOT_ALLOWED: "해당 메소드는 이 리소스에서는 사용할 수 없습니다.",
    status.HTTP_406_NOT_ACCEPTABLE: "요청한 자원이 요청 헤더에 정의된 내용으로는 생성될 수 없습니다.",
    status.HTTP_407_PROXY_AUTHENTICATION_REQUIRED: "이 요청을 처리하기 전에 프록시 인증이 필요합니다.",
    status.HTTP_408_REQUEST_TIMEOUT: "서버가 요청을 기다리다가 시간이 초과되었습니다.",
    status.HTTP_409_CONFLICT: "요청이 현재 리소스의 상태와 충돌합니다.",
    status.HTTP_410_GONE: "요청한 리소스는 영구적으로 이동되었으며, 앞으로 사용할 수 없습니다.",
    status.HTTP_411_LENGTH_REQUIRED: "Content-Length가 요청에 없기 때문에 서버가 요청을 거절했습니다.",
    status.HTTP_412_PRECONDITION_FAILED: "요청의 전제 조건이 서버에 의해 만족되지 않았습니다.",
    status.HTTP_413_REQUEST_ENTITY_TOO_LARGE: "요청된 엔티티가 서버가 처리할 수 있는 크기를 초과했습니다.",
    status.HTTP_414_REQUEST_URI_TOO_LONG: "요청 URI가 너무 길어 서버가 처리할 수 없습니다.",
    status.HTTP_415_UNSUPPORTED_MEDIA_TYPE: "요청된 미디어 유형이 서버에 의해 지원되지 않습니다.",
    status.HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE: "요청한 범위가 서버에서 처리할 수 있는 범위를 벗어났습니다.",
    status.HTTP_417_EXPECTATION_FAILED: "서버가 요청 헤더의 기대치를 만족시킬 수 없습니다.",
    status.HTTP_418_IM_A_TEAPOT: "이 서버는 주전자로, 커피를 끓일 수 없습니다. (장난스러운 코드)",
    status.HTTP_421_MISDIRECTED_REQUEST: "요청이 처리될 수 없는 서버로 잘못 전송되었습니다.",
    status.HTTP_422_UNPROCESSABLE_ENTITY: "요청된 콘텐츠는 올바르게 이해되었지만, 포함된 지시를 서버가 처리할 수 없습니다.",
    status.HTTP_423_LOCKED: "요청된 리소스가 잠겨 있어 접근할 수 없습니다.",
    status.HTTP_424_FAILED_DEPENDENCY: "이 요청은 다른 요청의 실패에 의존적이어서 실패했습니다.",
    status.HTTP_425_TOO_EARLY: "서버가 요청을 처리하기에는 아직 이르다고 판단했습니다.",
    status.HTTP_426_UPGRADE_REQUIRED: "서버가 클라이언트에 다른 프로토콜로 업그레이드할 것을 요청합니다.",
    status.HTTP_428_PRECONDITION_REQUIRED: "서버가 요청이 특정 조건을 충족하길 바라며, 그렇지 않으면 요청을 거부할 것입니다.",
    status.HTTP_429_TOO_MANY_REQUESTS: "단기간에 너무 많은 요청이 이루어졌습니다.",
    status.HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE: "요청 헤더가 너무 커서 서버가 처리할 수 없습니다.",
    status.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS: "법적인 이유로, 예를 들어 검열 또는 정부 지시에 의해, 컨텐츠가 접근 불가능한 상태입니다.",
    # 5xx: 서버가 요청을 처리하는 과정에서 문제가 발생했음을 나타냅니다.
    status.HTTP_500_INTERNAL_SERVER_ERROR: "서버 내부에 문제가 발생하여 요청을 처리할 수 없습니다.",
    status.HTTP_501_NOT_IMPLEMENTED: "서버가 요청 기능을 제공하지 않아서 처리할 수 없습니다.",
    status.HTTP_502_BAD_GATEWAY: "게이트웨이 문제로 인해 상위 서버로부터 잘못된 응답을 받았습니다.",
    status.HTTP_503_SERVICE_UNAVAILABLE: "서버가 일시적으로 요청을 처리할 수 없는 상태입니다, 과부하나 유지 보수 때문일 수 있습니다.",
    status.HTTP_504_GATEWAY_TIMEOUT: "게이트웨이 시간 초과로 인해 상위 서버로부터 응답을 받지 못했습니다.",
    status.HTTP_505_HTTP_VERSION_NOT_SUPPORTED: "서버가 요청에 사용된 HTTP 버전을 지원하지 않습니다.",
    status.HTTP_506_VARIANT_ALSO_NEGOTIATES: "내용 협상 과정에서 서버가 순환 참조를 발견했습니다.",
    status.HTTP_507_INSUFFICIENT_STORAGE: "서버에 요청을 처리하기 위한 충분한 저장 공간이 없습니다.",
    status.HTTP_508_LOOP_DETECTED: "서버가 요청 처리 중에 무한 루프를 감지했습니다.",
    status.HTTP_510_NOT_EXTENDED: "요청을 처리하기 위해 서버가 추가 기능을 필요로 합니다.",
    status.HTTP_511_NETWORK_AUTHENTICATION_REQUIRED: "네트워크 액세스를 얻기 위해서는 클라이언트의 인증이 필요합니다.",
}
